### ISSUE TITLE
install.php gets downloaded instead of executed

### ISSUE THREAD

**Issue by Morgy93** [psi-4ward/docker-contao#1]
Hello,

after running your image and downloading contao LTS `curl -L http://download.contao.org/lts | tar -xzp` I'm getting to the "incomplete installation" page which is fine so far.
Now I'm trying to open up the `/contao/install.php` to finish the installation, the file just gets downloaded, instead of executed.

Any help?

**Comment by psi-4ward** [comment]
Hmm works for.

Can you exactly explain your streps?

1.) Start the container: `docker run -p 80:80 --volume ~my-contao:/var/www/ -e RUN_UID=1000 --name contao psitrax/contao`
2.) exec into the container: `docker exec -ti contao bash`
3.) become apache: `su apache`
4.) Fetch and extract contao: `curl -sSL http://download.contao.org/lts | tar -xzp --strip 1`
5.) open `http://localhost/contao/install.php`

**Comment by Morgy93** [comment]
My `docker-compose.yml` and your method both result in the same behaviour.
The fun part is .. I found out that it does NOT work with Chrome, but does work with Edge and Firefox.
If you cannot confirm this, then let's just close this one and I'll report back if I run into other issues. =)

**Comment by psi-4ward** [comment]
Pls paste your docker-compose.yml

I've tested it with latest chromium and it works

**Comment by Morgy93** [comment]
```
mysql:
    image: mariadb
    volumes:
        - ./db/:/var/lib/mysql/
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=contao

contao:
    image: psitrax/contao
    links:
        - mysql:mysql
    ports:
        - 80:80
    volumes:
        - ./contao/:/var/www/
    environment:
        - RUN_UID=1000
        - XDEBUG=false
        - PHP_VALUE=max_execution_time=90,memory_limit=512M
```

I tried multiple things yesterday and I couldn't get it to work with Chrome.
It always downloads the install.php but if I rename it (doesn't matter what), then it loads. (CSS and stuff seems to be broken then, but php loads)
Maybe that's due to some weird environmental stuff on my side, but I don't care, since it's just the install.php and just with Chrome - everything else works just fine. (Even with Chrome)

Thanks for your awesome image. =)
